### ISSUE TITLE
API returns FuseResult<>, is that what we want?

### ISSUE THREAD

**Issue by rti** [dot-base/icd-10-api#46]
Do we really want this datatype being used on the wire? In order to use it properly, the client needs the same version of the Fuse library installed...

**Comment by rti** [comment]
might be related to #40

**Comment by velramiir** [comment]
Discussed this with @andreakreichgauer and we decided to stick to the search results in the response, because we want to keep the score of each result. Downstream services like the data-graph have to retrieve the CodeSystem from the item property.
