### ISSUE TITLE
Fix incorrect extension on Condition

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/icd-10-api#55]
### 🔥 Bug Description
Currently, the API returns Condition with incorrect extensions - they are missing a url value. This at least happens on `displayCopy`. 

### 🔍 Steps to Reproduce the Bug
1. Was recognized due to a [frontend bug](https://github.com/dot-base/medical-dashboard/issues/new?assignees=&labels=Type%3A+Bug&projects=&template=bug.md&title=) in production 

### 🧯 Possible Solution
* Quickfix: Set String value for URL. 
* Check why this extension is added and if it is really needed. I think we added it to not only search on icd codes but also there "chapter"-descriptions

### 🚧 Important
If extensions are removed from ICD-10-Api, this Issue would also need a migration on exisitng data

**Comment by velramiir** [comment]
This was probably caused by old data, because the current API version does not return any extensions.

**Comment by andreakreichgauer** [comment]
This was already fixed with https://github.com/dot-base/icd-10-api/pull/25.
The error only came up again due to existing Conditions that need a migration. I opened an issue for this https://github.com/dot-base/fhir-resources/issues/454
